
" 
" Archivo de configuracion de GVim personalizado
" Autor: Ricardo Daniel Quiroga
" Ultima Modificacion: 11/03/2014
" Email: l2radamanthys@gmail.com
" Licencia: GPL3


set nocompatible              " be iMproved, required
filetype off                  " required


set rtp+=$VIM/vimfiles/bundle/vundle/
" let path='$VIM/vimfiles/bundle'   
call vundle#rc()


" Plugins Instalar
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

Bundle 'gmarik/vundle'
Bundle 'scrooloose/nerdtree'
Bundle 'jistr/vim-nerdtree-tabs' 
Bundle 'scrooloose/nerdcommenter'
Bundle 'msanders/snipmate.vim'
Bundle 'taglist.vim'
Bundle 'AutoComplPop'
Bundle 'FindFile'


filetype plugin indent on

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


" Esquema de Colores
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" El Esquema de colores solo se cambiara si esta en modo GUI
if has('gui_running')
    colorscheme rDark 
else
    colorscheme Default
endif

" Ajustar Configuracion para windows
"if has('win_32') || has('win_16')
"    set backupdir="%HOMEPATH%"
"else
"    set backupdir=/home/wyrven/.vimback
"endif

" abrir cada bufer en una nueva pestaña 
"Alerta: Esto da problema si queres usar plugins como NERDtree
":au BufAdd,BufNewFile * nested tab sball

" Opciones de Plegado
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
hi Folded guibg=Gray5
set foldcolumn=1
set foldmethod=indent
set foldlevel=100                   " Evita que aparesca plegado cambiar por 1 para plegar todo

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
syntax on                           " resaltar sintaxis
set guifont=Source_Code_Pro:h10     " fuente 
set helplang=es                     " lenguaje de la Ayuda
set number                          " mostrar numero de linea
set fileencoding=utf-8              " codificacion de texto
set expandtab                       " Espacios en ves de tabulaciones
set tabstop=4                       " tamaño tabulacion
retab                               
set shiftwidth=4                    " identacion tamaño y que sea automatica
set autoindent 
set paste                           " Desactivar esta entrada soluciona supuestamente el problema de autocomplete de Snipmate
set ic

set autochdir                       " Cambiar el directorio actual al archivo abierto
autocmd BufEnter * silent! lcd %:p:h

" funcion normal (no vim normal sino mas conocido) de la tecla backspace activo osea poder borrar 
set backspace=eol,start,indent

" set mouse=v
set showmode                        " muestra el modo actual de VIM Normal/Edicion/Visor
set nobackup                        " backup de archivos desactivado
set ruler
set showcmd                         " muestra la convinacion de teclas actual
set nowrap                          " desactiva el cortado de linea
set hlsearch
set ignorecase                      " ignora mayusculas y minusculas en las busquedas
set nohlsearch                      " no resaltar los resultados de la busqueda esto marea
set title                           " mostrar la ruta completa del archivo que se edita
set undolevels=500                  "deshacer casi infinito
"set history=20                      "historia de comandos

highlight ColorColumn guibg=Gray8   " color de la columna 80
set colorcolumn=80                  " colorea la columna 80

" resalta la linea actual del cursor
set cursorline

set guitablabel=\[%N\]\ %t\ %M 

" Mapeo de Teclas
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Guardado clasico de Ctrl + S
map <C-s> :w<CR>
imap <C-s> <Esc>:w<CR>i

nmap _nt tabn
nmap _pt tabp
nmap _ft tabfirst
nmap _lt tablast


" Otra Configuracion
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" pestañas
nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>
nnoremap <silent> <A-Left> :execute 'silent! tabmove ' . (tabpagenr()-2)<CR>
nnoremap <silent> <A-Right> :execute 'silent! tabmove ' . tabpagenr()<CR>

" una ventana un poco mas grande
au GUIEnter * set lines=30 columns=100

" Configuracion de NERDTree
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let NERDTreeHighlightCursorline=1
let NERDTreeStatusline='-- Ficheros --'
let NERDTreeIgnore=['\.pyc$','\.back$', '\~$','\.swp$', '\.exe$']
let NERDTreeAutoCenterThreshold=1
let NERDTreeMinimalUI=1
let NERDTreeMapOpenInTab='<2-LeftMouse>'

let g:nerdtree_tabs_open_on_console_startup=0 "no abrir al inicio
let g:nerdtree_tabs_open_on_gui_startup=0 "no abrir al inicio

let NERDTreeDirArrows=1

map <F2> :NERDTreeToggle<CR>
"map <F4> :NERDTreeTabsToggle<CR>

" Configuracion de TagList
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"let Tlist_Auto_Open=1
let Tlist_Sort_Type= 'name'
let Tlist_Compact_Format=1
let Tlist_Show_Menu=1
let Tlist_Show_One_File=1
let tlist_php_settings='php;f:function'   " No muestra las variable

map <F3> :TlistToggle<CR>

" Configuracion de la barra de estado
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
hi StatusLine guibg=gray ctermbg=gray

set laststatus=2                         " barra de estado siempre visible
set statusline =Archivo:\ %t
set statusline +=\ T:\ %y\ LB:\ [%{&ff}] " tipo y codificacion 
set statusline +=\ Bufer:\ %n
" right align
set statusline +=%=
set statusline +=\ Linea:\ %04l\ de:\ %04L\ \ |

" Configuracion especial de Sintaxis para Python
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
syn sync fromstart                      "problemas de resaltado de sintaxis comunes

let python_version_2=1                  " Por Defecto la Version de Sintaxis de python es 2.x
let python_highlight_all=1              " Resaltado de Sintaxis para todo

map <F5> :!python %<CR>

