comandos:
	@echo "COMANDOS"
	@echo ""
	@echo "install"
	@echo "diff_config"
	@echo "diff_alias"
	@echo ""

install:
	@cp .zshrc ~/.zshrc
	@cp .my_aliases ~/.my_aliases

diff_config:
	@diffuse .zshrc ~/.zshrc

diff_alias:
	@diffuse .my_aliases ~/.my_aliases
